name: Build and Cache

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main]

env:
  CI_ENVIRONMENT: "true"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: |
            .next/cache
            node_modules/.cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          # No real credentials needed - mock will be used automatically
          NEXT_PUBLIC_SUPABASE_URL: https://mock-project.supabase.co
          NEXT_PUBLIC_SUPABASE_ANON_KEY: mock-anon-key

      - name: Run tests
        run: npm test
