name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test || echo "No tests found"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Verify artifacts exist
        run: |
          # Check if all required paths exist before uploading
          missing_paths=()
          
          if [ ! -d ".next" ]; then
            missing_paths+=(".next")
          fi
          
          if [ ! -d "public" ]; then
            missing_paths+=("public")
          fi
          
          if [ ! -f "package.json" ]; then
            missing_paths+=("package.json")
          fi
          
          if [ ! -f "package-lock.json" ]; then
            missing_paths+=("package-lock.json")
          fi
          
          if [ ! -f "next.config.js" ]; then
            missing_paths+=("next.config.js")
          fi
          
          if [ ${#missing_paths[@]} -ne 0 ]; then
            echo "Error: The following required paths are missing: ${missing_paths[*]}"
            exit 1
          fi
          
          echo "All required paths exist, proceeding with artifact upload."
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: |
            .next/
            public/
            package.json
            package-lock.json
            next.config.js

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-files
          path: .
      - name: Check downloaded artifacts
        run: |
          echo "Current directory structure:"
          ls -la
          echo "Next.js build directory structure:"
          ls -la .next/ || echo ".next directory not found"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: vibing-prod:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
